### ISSUE TITLE
/api-calls "make request" is broken

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#106]
http://syncfor.science/api-calls/ is returning "error" on running any request. For example:

![image](https://user-images.githubusercontent.com/313089/27352412-a5de8318-55ce-11e7-8522-a38dc0a73e59.png)

**Comment by erikwiffin** [comment]
I don't think I have access to the machine running at portal.demo.syncfor.science. You moved it to `s4sawsbig` a while ago and I can only get to `s4s-aws`.

My `.ssh/config` entry is

```
 Host portal.syncfor.science
     HostName 52.205.223.91
     User erik
     IdentityFile ~/.docker/machine/machines/staging-1/id_rsa
```

**Comment by jmandel** [comment]
Gotcha. Can you share your preferred public key and I'll add you to the
list?

**Comment by jmandel** [comment]
Logs show:

```
smart_1               | [2017-09-10 04:26:34,718] ERROR in app: Exception on /api/open-fhir/metadata [GET]
smart_1               | Traceback (most recent call last):
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1988, in wsgi_app
smart_1               |     response = self.full_dispatch_request()
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1641, in full_dispatch_request
smart_1               |     rv = self.handle_user_exception(e)
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1544, in handle_user_exception
smart_1               |     reraise(exc_type, exc_value, tb)
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
smart_1               |     raise value
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1639, in full_dispatch_request
smart_1               |     rv = self.dispatch_request()
smart_1               |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1625, in dispatch_request
smart_1               |     return self.view_functions[rule.endpoint](**req.view_args)
smart_1               |   File "./auth_proxy/views/api/views.py", line 61, in api_open_fhir_proxy
smart_1               |     response = proxy_service.api(url, request)
smart_1               |   File "./auth_proxy/services/proxy.py", line 50, in api
smart_1               |     return proxy.proxy()
smart_1               |   File "./auth_proxy/proxy/__init__.py", line 85, in proxy
smart_1               |     request = self.client.request()
smart_1               |   File "./auth_proxy/proxy/flask.py", line 54, in request
smart_1               |     args.append(('_security', self._scope_security()))
smart_1               |   File "./auth_proxy/proxy/flask.py", line 89, in _scope_security
smart_1               |     return ','.join(['public'] + self.orig.oauth.access_token.security_labels)
smart_1               |   File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 343, in __getattr__
smart_1               |     return getattr(self._get_current_object(), name)
smart_1               | AttributeError: 'Request' object has no attribute 'oauth'
```

@erikwiffin can you take a look at this? You should have ssh access to `ubuntu@demo.syncfor.sciencef` now.

**Comment by mtmcduffie** [comment]
It looks like the patient one is failing because that patient record example doesn't exist anymore. I'll dig into the others after I send you my key to get added to that machine.

diagnostics | Resource Patient/smart-1288992 is not known

**Comment by mtmcduffie** [comment]
Re-running test data import fixed the patient issues. The other issues were because the latest version of the code wasn't running I believe. I think this is the important commit that was missing.

https://github.com/sync-for-science/auth-proxy/commit/1013909226079c11da660b6d01f54cb0c145ce48

Now all of them aside from the patient call are returning empty result sets. If it's important we should create another task to check on the test data.
