### ISSUE TITLE
Can't run behave tests from localhost

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#34]
I see the following when I try to run locally via docker (same error, post-authorization -- which appears to work -- on all vendors I've tried). I see equivalent behavior when I connect via browser, too.

```
$ docker run -p 9003:5000 -e VIRTUAL_HOST=tests.dev.syncfor.science:9003 --rm -it tests /bin/bash
root@fb458a5a500b:/demo-test-suite# VENDOR=smart behave
Exception KeyError: 'state'
Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python3.5/site-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python3.5/site-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python3.5/site-packages/behave/runner.py", line 471, in run_model
    self.run_hook('before_all', context)
  File "/usr/local/lib/python3.5/site-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 46, in before_all
    context.oauth.authorize()
  File "/demo-test-suite/testsuite/oauth/authorization_code.py", line 49, in authorize
    code = self.request_authorization()
  File "/demo-test-suite/testsuite/oauth/authorization_code.py", line 58, in request_authorization
    code = self._authorizer.authorize()
  File "/demo-test-suite/testsuite/oauth/authorize/base.py", line 48, in authorize
    return self._get_authorization()
  File "/demo-test-suite/testsuite/oauth/authorize/base.py", line 78, in _get_authorization
    self._check_state(''.join(query['state']))
KeyError: 'state'
```

**Comment by jmandel** [comment]
Appears to happen only with phantomjs, not chrome.
Potential fix: move to chrome everywhere.

**Comment by jmandel** [comment]
Fixed with move to chrome everywhere.
