### ISSUE TITLE
Lab observation traceback is missing information

### ISSUE THREAD

**Issue by jmandel** [sync-for-science/tracking#71]
For athenahealth, this traceback is confusing the team:

```
And there exists a fixed Observation.code.coding.system=http://loinc.org 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1456, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.5/site-packages/behave/model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features/steps/argonaut.py", line 191, in step_impl
    assert value in found, utils.bad_response_assert(context.response,
TypeError: argument of type 'NoneType' is not iterable
```

Instead of `TypeError`, we should show the offending data.

**Comment by jmandel** [comment]
Note: this happens for vitals, too
